### ISSUE TITLE
[Docs] Play next from and array of source

### ISSUE THREAD

**Issue by NewSphinx** [morinted/rehowl#9]
Say I provided an array of sources, and I wanna trigger the start of the second audio in the array. How do I do that?

Also, If I change the order in the source array, does it trigger a network request again for something that was already loaded? if no, On what basis does it decide whether to re-fetch or not?

Also also, thank you.

**Comment by morinted** [comment]
In howler.js, the source array is for compatability -- they are fallbacks
in different formats. In order to play multiple sounds, you'll need
multiple useHowl calls.

Another developer maintained multiple useHowls, one for the current file,
one for the next, and then swapped between the two to play a list of files.

**Comment by NewSphinx** [comment]
Oh okay, thanks. Should've read the docs thoroughly :P
